"""creating Threat table v1.0

Revision ID: 114359c74d66
Revises: f867c5ef3cb3
Create Date: 2025-10-22 00:21:34.792658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '114359c74d66'
down_revision: Union[str, Sequence[str], None] = 'f867c5ef3cb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Threats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin', sa.UUID(), nullable=False),
    sa.Column('threat_level', sa.Enum('NONE', 'LOW', 'MEDIUM', 'HIGH', 'ULTRA', name='threatlevels'), nullable=False),
    sa.Column('threat_status', sa.Enum('ACTIVE', 'MONITORING', 'CLOSED', name='threatstatus'), nullable=False),
    sa.Column('predicted_age', sa.Integer(), nullable=True),
    sa.Column('predicted_sex', sa.String(length=10), nullable=True),
    sa.Column('predicted_emotion', sa.String(length=255), nullable=True),
    sa.Column('face_confidence', sa.Integer(), nullable=True),
    sa.Column('weapon_confidence', sa.Integer(), nullable=True),
    sa.Column('predicted_weapon', sa.String(length=255), nullable=True),
    sa.Column('detected_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Threats_admin'), 'Threats', ['admin'], unique=False)
    op.create_index(op.f('ix_Threats_id'), 'Threats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Threats_id'), table_name='Threats')
    op.drop_index(op.f('ix_Threats_admin'), table_name='Threats')
    op.drop_table('Threats')
    # ### end Alembic commands ###
